#!/bin/sh

set -e

case "${1}" in
  prereqs)
    exit 0
    ;;
esac

if ! grep -q firstboot /proc/cmdline; then
  exit 0
fi

. /scripts/functions

log_begin_msg "Running fstrim..."

fstrim "${rootmnt?}/" ||:

log_end_msg

exit 0
